apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-operator
  namespace: chaos-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-operator
rules:
- apiGroups: ["chaos-platform.io"]
  resources: ["chaosexperiments"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-operator
subjects:
- kind: ServiceAccount
  name: chaos-operator
  namespace: chaos-platform
roleRef:
  kind: ClusterRole
  name: chaos-operator
  apiGroup: rbac.authorization.k8s.io
