apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaos-platform.fullname" . }}-secret
  labels:
    {{- include "chaos-platform.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded values
  example-key: {{ "example-value" | b64enc | quote }}
